export const ERROR_CODES = {
  INTERNAL_SERVER_ERROR: 'ERR_INTERNAL_SERVER',
  INVALID_REQUEST: 'ERR_INVALID_REQUEST',
  TOKEN_EXPIRED: 'ERR_TOKEN_EXPIRED',
  REFRESH_TOKEN_EXPIRED: 'ERR_REFRESH_TOKEN_EXPIRED',
  UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  INVALID_TOKEN: 'ERR_INVALID_TOKEN',
  INVALID_REFRESH_TOKEN: 'ERR_INVALID_REFREH_TOKEN',
  NO_TOKEN: 'ERR_NO_TOKEN',
  NO_REFRESH_TOKEN: 'ERR_NO_REFRESH_TOKEN',
  TOO_MANY_REQUESTS: 'ERR_TO_MANY_REQUESTS',
};
