export const AUTH_ERROR_CODES = {
  USER_ALREADY_EXISTS: 'ERR_AUTH_USER_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'ERR_AUTH_INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'ERR_AUTH_USER_NOT_FOUND',
  USER_ALREADY_VERIFIED: 'ERR_AUTH_USER_ALREADY_VERIFIED',
  USER_NOT_VERIFIED: 'ERR_AUTH_USER_NOT_VERIFIED',
  INVALID_PROVIDER: 'ERR_AUTH_INVALID_PROVIDER',
  INVALID_ID_TOKEN: 'ERR_AUTH_INVALID_ID_TOKEN',
  MISSING_CODE_OR_PROVIDER: 'ERR_AUTH_MISSING_CODE_OR_PROVIDER',
};
