export const AUTH_ERROR_CODES = {
  USER_ALREADY_EXISTS: 'ERR_AUTH_USER_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'ERR_AUTH_INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'ERR_AUTH_TOKEN_EXPIRED',
  UNAUTHORIZED: 'ERR_AUTH_UNAUTHORIZED',
  INVALID_TOKEN: 'ERR_AUTH_INVALID_TOKEN',
  NO_TOKEN: 'ERR_AUTH_NO_TOKEN',
  USER_NOT_FOUND: 'ERR_AUTH_USER_NOT_FOUND',
  USER_ALREADY_VERIFIED: 'ERR_AUTH_USER_ALREADY_VERIFIED',
  USER_NOT_VERIFIED: 'ERR_AUTH_USER_NOT_VERIFIED',
};
